route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'Email'

  routes:
  - match:
      severity: 'critical'
    receiver: 'Email'
    repeat_interval: 2h
    continue: true
  - match:
      severity: 'warning'
    receiver: 'Email'
    repeat_interval: 1d
    continue: true

global:
  smtp_smarthost: 'smtp.domain.com:587'
  smtp_from: 'your-email@domain.com'
  smtp_auth_username: 'your-email@domain.com'
  smtp_auth_password: 'app-password'  # Use App Password if 2FA enabled
  smtp_require_tls: true

receivers:
  - name: 'Email'
    email_configs:
       - to: 'your-email@domain.com,your-email2@domain.com'
         send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

#templates:
#  - '/opt/alertmanager/templates/*.tmpl'
